language: python
python:
  - "3.6"
cache: pip
install:
  - pip install nose
  - pip install -r requirements.txt
  - pip install coveralls
  
script:  
   - nosetests --exe -v --with-coverage --cover-package=app
   
after_success:
   - coveralls  